### ISSUE TITLE
some module missing

### ISSUE THREAD

**Issue by nssreenivasalu** [overflowjs-com/Angular8-CRUD-employee-management#2]
An unhandled exception occurred: Could not find module "@angular-devkit/build-angular"

**Comment by lalit-aggarwal** [comment]
Hi,

Thank you for your concern.

I have not checked in the node modules. 

You need to run the following command to install all the dependencies.

> npm install

After running this command, you can run the application using "ng serve" command.

Let me know if you still face any issues.

Regards,
Lalit Aggarwal
